apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'
spec:
  jobs:
    - name: tests
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Record test results to Launchable workspace
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          report_path: './report.xml'
          test_runner: go-test
        if: always()
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}