apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        uses: docker://golang:1.20 #unsure about this uses
        run: go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Record test results to Launchable workspace
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          report_path: './report.xml'
          test_runner: go-test
        if: always()
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}