name: GoTest test process

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: go test -v ./...  #| go-junit-report -set-exit-code > report.xml

      - name: Verify Launchable Results #not sure if its the right order or not
        run: launchable verify || true  # Add this step for verification



      - name: Record test results to Launchable workspace
        uses: launchableinc/record-build-and-test-results-action@v1.0.0
        with:
          test_runner: go-test
          report_path: './report.xml'
        if: always()
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
